language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test --module-resolution=node --npm --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node
  --npm --plugin sauce --job-name "star-rating:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
env:
  global:
  - secure: Nd8SNU1MVXPxlfcbzLaTmgqAi3BrAHLxvvjTTWnuoNBiLjHaX1OZuPb9cAlVk/HeVD3uH5AvI1+IozPyUBO78YEbs1HxqWHPNaz76HBSql3Q3niPBVwVtGVx6FeNQfBkfOffs1ghurU8M18jsIElr4X/zy+hoYjnnBrWS1Qr+v7nMrK7n9bjunYIKJcpAwiDWEGq4+nibza+96e1hOUEwfS7/OoZJ8vUwcx+S/FtwNwgPm/OyUzF1Csd3PymNAZ7SDbbfpL9XOYmKyA1KPbHiP68NxR3i3DdCAQpNlrW4buA1xAWxX5GEAFCPO0Hi0Pd0skQkKdDhImDH4J9lEJE72r4PgdgMfo/XnpLGOTpZpl70pDVmxGkhGh/UiGlmHx9oX92Fe1MLZuKBekDqyy37POM1ICxUx/jDmC0wSR+TODGgEDi8juOtCU+CauOOIT5KdITg4VWDBZHNGefyDpBtYbLvk8CkG3fuy3611ZdSomd8sfSwGAvbnKrZDmw3dZkeReEak8FwSxCH/lh4pCSX2izeaqAqjvsfk2+XkmD1rLd1y/0RdPr8zrURtQ958VRrANsm7A5nDaVg7/J4DEcFxmPA0UcBH3Oq3bIsf/qz5wkycVwi95PIf8DvEpsq/nn3LxUzodnRd7jxGbq9WTHWhUD4SucvurAPkt4VV2GTeU=
  - secure: DhLG80a3KIMU+D7dy5e4Asq59aVpEL9Mwzik5KBa6R49plHn0Qaf6k96KmRV8gWB8hBehYGEEofVmb6DuFafLT1S7k1gCDbTOwgAeVE8zQ7OjDsduzSD/hsPvHU/HWWBq+BpKn61034V2vR9p/BNK4LYcrv+Oyz+m/dEv3d2M3d0CzJAuPXo3pEXSsmAmOvu8AG/DXV/yp7m3yFLzQ5B++TaG7sfTgHEzDgEJisygWzTnjuDTNx+blFccekoU/DOBxWaiBmUDNq3FHIivs8ZH+yqwhASWgBiX6ZiIsZ31jLcRtIpPXeeuIhTQmthsM2x7OIkAE7bSIf2ZH00QCPUNqa5UZ8h3t8k2j9WWtt2zNX/4kwXhFafaw6gBSDhUAzRMQM6AmuAt9IMqY5CJvKEp90G2MLyiuSJc5BoZCo/0BmWijv3oi4gyBTt+nNLatJiT0HH41dRWes5Ow4YrBCCORZ+WsJ8c8tjdUFDQjpAMsYRdwpdjeSvujbL5b4wUWRduB31Tif9D1LB4azqtkPgmlMMGIfPtTkMBOVd+4B/dnc3S2hVeVQpJWfYylk1XvIX20hzIxRXeCJMIEGgUGsGkZFHP1wm+/iyqjLjvWHjEQ/Ou2T03wid0k7N+kk8jRwLZh7fVlSUYdoOdEE5khgyN03hjl3/WeyCb9mYAz5z67s=
